spring:
    datasource:
      platform: postgres
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:userdb;NON_KEYWORDS=USER
      username: sa
      password:
        jpa:
          database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-ui
      flyway:
        schemas: userdb
        locations: classpath:db/migration
      jpa:
        show-sql: true
        generate-ddl: false
        properties:
          hibernate:
            ddl-auto: none

---
spring.jpa.open-in-view: false