server:
  port: 8183

logging:
  level:
    org.springframework.web: DEBUG
    co.uk.bank.usercrud: DEBUG
    org.hibernate: DEBUG
    org: INFO

spring:
  application:
    name: user-bank
  profiles:
    active: prod

---

retry.maxAttempts: 2
retry.maxDelay: 100

---

logging.level.root: WARN
logging.level.co.uk.bank.usercrud: DEBUG